### ISSUE TITLE
Install Stuck on Clearing Forwarded Ports

### ISSUE THREAD

**Issue by lreynish** [NCSU-Libraries/Suma-Vagrant#2]
Hello: I'm trying to install Suma-Vagrant to try out Suma and the vagrant up process is stuck at:

"Clearing any previously set forwarded ports...." (see attached screenshot)

The machine I'm installing on is Windows 7 32-bit with version 5.0.24 of Virtual Box and version 1.8.4 of Vagrant.

![vagrant up stalled](https://cloud.githubusercontent.com/assets/20363473/16704005/966fa8a4-452f-11e6-908c-b7be912b6317.JPG)

Thanks for any help.

**Comment by bretdavidson** [comment]
Hi,

Thanks for trying out Suma. I've pushed a small change to the Vagrantfile that might fix this issue. Could you try downloading or cloning Suma-Vagrant again and running `vagrant up` with the updated Vagrantfile? You may need to note the ports that Vagrant forwards to (this will be listed in the progress log).

Thanks,

Bret

**Comment by lreynish** [comment]
Hi Bret,

Thanks for the quick response! I downloaded the newer vagrantfile as requested and the two changes I observed are:

1) It noted that a newer version of the box 'ubuntu/trusty32 is available.

2) I saw the progress log about the port collision. It is now stuck at that point (see screen shot).

![vagrant up stalled](https://cloud.githubusercontent.com/assets/20363473/16779938/9c48a5be-4831-11e6-933a-bb3c9294e74f.JPG)

**Comment by lreynish** [comment]
Whoops - should put the correct screen shot:

![vagrant up stalled 2](https://cloud.githubusercontent.com/assets/20363473/16779960/b2f3df2c-4831-11e6-8dac-fffabe1c14c2.JPG)

**Comment by bretdavidson** [comment]
Two ideas:

1) It might be worth trying these commands from within something like [GitHub Desktop](https://desktop.github.com/).

2) Do you have any firewalls enabled?

I've actually reverted the previous change to auto_correct, so you may want to update your clone or download again. Thanks for your patience as we work through this.

Best,

Bret

**Comment by lreynish** [comment]
Hi Bret:

1) I will download that and install it.

2) No software firewalls (Windows or third-party) but there is a hardware firewall around the organization. If that needs adjusting I can ask our network admin to do so.

Thank you for following up.
