### ISSUE TITLE
'ansible_local' and 'timezone' provisioners could not be found

### ISSUE THREAD

**Issue by sjsafranek** [NCSU-Libraries/Suma-Vagrant#3]
I am running this on Debian Jessie

vagrant up
Installing the 'vagrant-vbguest' plugin. This can take a few minutes...
Installed the plugin 'vagrant-vbguest (0.13.0)'!
Updating plugins: vagrant-vbguest. This may take a few minutes...
All plugins are up to date.
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The 'ansible_local' provisioner could not be found.
* The 'timezone' provisioner could not be found.

**Comment by bretdavidson** [comment]
Hi Stefan,

Thanks for reaching out about Suma-Vagrant. What version of Vagrant are you
using? Could you confirm that you are using the latest version (1.9.1)?

Bret
